import Math from './models/Math.js';
import Random from './models/Random.js';
import Style from './models/Style.js';
declare const _default: {
    Math: {
        E: number;
        LN10: number;
        LN2: number;
        LOG10E: number;
        LOG2E: number;
        PI: number;
        SQRT1_2: number;
        SQRT2: number;
        abs(number: number): number;
        acos(number: number): number;
        acosh(number: number): number;
        asin(number: number): number;
        asinh(number: number): number;
        atan(number: number): number;
        atan2(x: number, y: number): number;
        atanh(number: number): number;
        cbrt(number: number): number;
        ceil(number: number): number;
        clz32(number: number): number;
        cos(number: number): number;
        cosh(number: number): number;
        dif(...numbers: number[]): number;
        exp(number: number): number;
        expm1(number: number): number;
        floor(number: number): number;
        fround(number: number): number;
        hypot(number: number): number;
        imul(x: number, y: number): number;
        log(number: number): number;
        log10(number: number): number;
        log1p(number: number): number;
        log2(number: number): number;
        max(...numbers: number[]): number;
        min(...numbers: number[]): number;
        pow(x: number, y: number): number;
        random(x?: number | undefined, y?: number | undefined): number;
        round(number: number): number;
        shuffle(...numbers: number[]): number | number[];
        sign(number: number): number;
        sin(number: number): number;
        sinh(number: number): number;
        sum(...numbers: number[]): number;
        sqrt(number: number): number;
        tan(number: number): number;
        tanh(number: number): number;
        trunc(number: number): number;
    };
    Random: {
        number(min: number, max: number): number;
        element(array: object | unknown[]): any;
        '__#1@#color'(): void;
    };
    Style: {
        TextStyle: typeof import('./models/Style.js').TextStyle;
        TextColor: typeof import('./models/Style.js').TextColor;
        BackgroundColor: typeof import('./models/Style.js').BackgroundColor;
        titleCase(string: string, lowercase?: boolean): string;
        pascalCase(string: string, lowercase?: boolean): string;
        stringCase(string: string, lowercase?: boolean): string;
        phraseCase(string: string, lowercase?: boolean): string;
        log(text: string, options: import('./models/Style.js').LogOptions): string;
    };
};
export default _default;
export { Math, Random, Style };
